### ISSUE TITLE
Missing Dollar Module

### ISSUE THREAD

**Issue by lando2319** [pselle/macvimspeak#2]
Strange this we working before now I am getting a compiler error "No Such Module 'Dollar'".

This is with just cloning the repo then opening the project and running the app.

Any thoughts on what's going on?

**Comment by pselle** [comment]
Hmm, so I went back and forth between installing via gitsubmodules and using Carthage. It looks like I have the Carthage stuff in there, so you may need to install it with that. In either case, you need to add Dollar to the embedded binaries in the "General" settings tab 

https://github.com/Carthage/Carthage#getting-started

**Comment by lando2319** [comment]
Thank you for your reply, "Dollar" appears to show up on the list, but it nonetheless says the module is missing. (see image)

![missingdollar copy](https://cloud.githubusercontent.com/assets/2363722/7653773/ec5f0a2c-fadd-11e4-9270-47ffc30c3df6.png)

**Comment by pselle** [comment]
Interesting. I've been able to resolve this when it happens by linking/unlinking/restarting XCode.

For full knowledge, do you have an Apple Developer license for either iOS or OSX?

**Comment by lando2319** [comment]
Yes I have a developers account. When I did a standard git clone, it leaves the directory "Dollar" empty.

**Comment by pselle** [comment]
Run `git submodule init` and `git submodule update` and it should download the files, I tried that in a new clone.

**Comment by lando2319** [comment]
Thanks for the suggestions, it looks like it successfully loaded the modules. Unfortunately it looks like the code needs to be updated to work with Swift 1.2, there were about 10 errors, autocorrect was able to fix some, but not all of the errors.

**Comment by louity** [comment]
It still doesn't work, autocorrect (xcode 7.3) fixed some issues but not all of them and I am unable to fix them beacause I don't know swift.
After autocorrect i have :
<img width="1280" alt="capture d ecran 2016-03-28 a 16 58 35" src="https://cloud.githubusercontent.com/assets/14196488/14080581/5db08e30-f506-11e5-97f0-1a81bd1e572a.png">
<img width="1280" alt="capture d ecran 2016-03-28 a 16 58 31" src="https://cloud.githubusercontent.com/assets/14196488/14080582/60b7e452-f506-11e5-9503-d3459ee31fd3.png">

**Comment by pselle** [comment]
Thanks, since those are within Dollar itself, I might need to upgrade the version of Dollar ...
