### ISSUE TITLE
Adding new bindings

### ISSUE THREAD

**Issue by k3yavi** [pselle/macvimspeak#5]
Hi,
I am wondering how can I add new key bindings?

**Comment by pselle** [comment]
Hi! Much delayed but this is probably what you're looking for: https://github.com/pselle/macvimspeak/blob/master/MacVimSpeak/KeyCode.swift. If you edit/recompile, you'll be able to add new key bindings.

**Comment by k3yavi** [comment]
Thanks @pselle
